//! AES-128 encryption-core generator.
//!
//! [`generate_aes128_enc`] returns synthesizable SystemVerilog for an iterative
//! (1 round/clock, on-the-fly key expansion) AES-128 encryption core. The S-box
//! `case` arms are emitted from [`crate::sbox::sbox_table`], so the table is
//! derived from the GF(2^8) field rather than hand-copied.
//!
//! The emitted RTL is verified against the FIPS-197 known-answer vectors by
//! `tests/verilog_kat.rs` (which runs Icarus Verilog when it is installed).

use crate::sbox::sbox_table;
use core::fmt::Write as _;

/// Supported AES variants. Phase 1 implements AES-128 only; the enum leaves
/// room for AES-192/256, which differ in round count and key-schedule width.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum AesVariant {
    Aes128,
}

impl AesVariant {
    /// Cipher-key width in bits.
    pub const fn key_bits(self) -> u32 {
        match self {
            AesVariant::Aes128 => 128,
        }
    }
    /// Number of cipher rounds.
    pub const fn rounds(self) -> u32 {
        match self {
            AesVariant::Aes128 => 10,
        }
    }
    /// Name of the generated top-level Verilog module.
    pub const fn top_module(self) -> &'static str {
        match self {
            AesVariant::Aes128 => "aes128_enc",
        }
    }
}

impl core::fmt::Display for AesVariant {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "AES-{}", self.key_bits())
    }
}

/// Cost/latency description of a generated core — the crypto analogue of the
/// overhead report produced by the ECC pass.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AesReport {
    pub variant_name: String,
    pub block_bits: u32,
    pub key_bits: u32,
    pub rounds: u32,
    /// `start` -> `done` latency in clock cycles (1 load + N rounds).
    pub latency_cycles: u32,
    /// Blocks in flight at once. This core is iterative, not pipelined.
    pub blocks_in_flight: u32,
}

impl AesReport {
    pub fn for_variant(v: AesVariant) -> Self {
        AesReport {
            variant_name: v.to_string(),
            block_bits: 128,
            key_bits: v.key_bits(),
            rounds: v.rounds(),
            latency_cycles: v.rounds() + 1,
            blocks_in_flight: 1,
        }
    }

    /// Throughput in bits/second for a given clock, useful for sizing a radio link.
    pub fn throughput_bps(&self, clock_hz: u64) -> u64 {
        (clock_hz / self.latency_cycles as u64) * self.block_bits as u64
    }

    /// One-line human summary for CLI output.
    pub fn summary(&self) -> String {
        format!(
            "{}: {}-bit blocks, {} rounds, {} cycles/block (iterative)",
            self.variant_name, self.block_bits, self.rounds, self.latency_cycles
        )
    }

    /// Minimal JSON object for embedding in an `hcp.json` manifest alongside
    /// the ECC report. Hand-rolled so this crate stays dependency-free; feed it
    /// into `serde_json::from_str` on the `hcp-package` side if you prefer.
    pub fn to_json(&self) -> String {
        format!(
            concat!(
                "{{\"scheme\":\"{}\",\"variant\":\"{}\",\"block_bits\":{},",
                "\"key_bits\":{},\"rounds\":{},\"latency_cycles\":{},",
                "\"blocks_in_flight\":{},\"pipelined\":false}}"
            ),
            "aes128",
            self.variant_name,
            self.block_bits,
            self.key_bits,
            self.rounds,
            self.latency_cycles,
            self.blocks_in_flight
        )
    }
}

/// Emit the S-box `case` arms, four entries per line.
fn emit_sbox_case() -> String {
    let table = sbox_table();
    let mut s = String::with_capacity(256 * 28);
    for row in 0..64 {
        s.push_str("            ");
        for col in 0..4 {
            let i = row * 4 + col;
            let _ = write!(s, "8'h{:02x}: sbox = 8'h{:02x};", i, table[i]);
            if col != 3 {
                s.push(' ');
            }
        }
        s.push('\n');
    }
    s.push_str("            default: sbox = 8'h00;\n");
    s
}

/// Generate the AES-128 encryption core as SystemVerilog source.
pub fn generate_aes128_enc() -> String {
    let mut out = String::with_capacity(16 * 1024);
    out.push_str(HEADER);
    out.push_str(MODULE_HEAD);
    out.push_str("    function automatic [7:0] sbox(input [7:0] a);\n");
    out.push_str("        case (a)\n");
    out.push_str(&emit_sbox_case());
    out.push_str("        endcase\n");
    out.push_str("    endfunction\n\n");
    out.push_str(DATAPATH);
    out
}

const HEADER: &str = "\
// -----------------------------------------------------------------------------
// aes128_enc.sv  --  AES-128 encryption core (FIPS-197)
//
// GENERATED by hcp-crypto. Do not edit by hand; edit the generator instead.
//   cargo run -p hcp-crypto --example emit > aes128_enc.sv
//
// Iterative: 1 round per clock, on-the-fly key expansion.
// Byte 0 occupies the MSB of each 128-bit port (matches FIPS-197 hex order).
// Handshake: pulse `start` for one cycle; `ciphertext` is valid when `done`
// pulses. The core then returns to idle and accepts the next block.
//
// Portable: no vendor primitives, no initial blocks, no inferred memories.
// Verified against FIPS-197 Appendix B and C.1 known-answer vectors.
// SPDX-License-Identifier: Apache-2.0
// -----------------------------------------------------------------------------
`default_nettype none

";

const MODULE_HEAD: &str = "\
module aes128_enc (
    input  wire         clk,
    input  wire         rst_n,       // synchronous, active-low
    input  wire         start,       // 1-cycle strobe
    input  wire [127:0] key,
    input  wire [127:0] plaintext,
    output reg  [127:0] ciphertext,
    output reg          done,        // 1-cycle strobe: ciphertext valid
    output reg          busy
);

";

// NOTE: shift_rows is written as pure bit-slicing (no `reg [7:0] b [0:15]`
// array). An array inside a function makes Yosys infer and then flatten a
// memory, and trips some Verilator lint rules. Explicit slices are equivalent
// hardware and fully portable.
const DATAPATH: &str = r#"    // ---- GF(2^8) helpers (AES field, modulus 0x11b) ----------------------
    function automatic [7:0] xtime(input [7:0] b);
        xtime = (b[7]) ? ((b << 1) ^ 8'h1b) : (b << 1);
    endfunction
    function automatic [7:0] mul2(input [7:0] b); mul2 = xtime(b);     endfunction
    function automatic [7:0] mul3(input [7:0] b); mul3 = xtime(b) ^ b; endfunction

    // ---- key-schedule helpers --------------------------------------------
    function automatic [31:0] subword(input [31:0] w);
        subword = {sbox(w[31:24]), sbox(w[23:16]), sbox(w[15:8]), sbox(w[7:0])};
    endfunction
    function automatic [31:0] rotword(input [31:0] w);
        rotword = {w[23:0], w[31:24]};
    endfunction

    // ---- round transforms -------------------------------------------------
    function automatic [127:0] sub_bytes(input [127:0] s);
        integer i;
        for (i = 0; i < 16; i = i + 1)
            sub_bytes[i*8 +: 8] = sbox(s[i*8 +: 8]);
    endfunction

    // ShiftRows. Byte n of the block occupies s[127-8*n -: 8], i.e. byte 0 is
    // the MSB. In column-major AES order, output byte n takes input byte
    // (n + 4*(n mod 4)) mod 16. Written out explicitly for portability.
    function automatic [127:0] shift_rows(input [127:0] s);
        shift_rows = {
            s[127:120], s[ 87: 80], s[ 47: 40], s[  7:  0],   // col 0: b0  b5  b10 b15
            s[ 95: 88], s[ 55: 48], s[ 15:  8], s[103: 96],   // col 1: b4  b9  b14 b3
            s[ 63: 56], s[ 23: 16], s[111:104], s[ 71: 64],   // col 2: b8  b13 b2  b7
            s[ 31: 24], s[119:112], s[ 79: 72], s[ 39: 32]    // col 3: b12 b1  b6  b11
        };
    endfunction

    function automatic [31:0] mix_col(input [31:0] col);
        reg [7:0] a0, a1, a2, a3;
        begin
            a0 = col[31:24]; a1 = col[23:16]; a2 = col[15:8]; a3 = col[7:0];
            mix_col[31:24] = mul2(a0) ^ mul3(a1) ^ a2       ^ a3;
            mix_col[23:16] = a0       ^ mul2(a1) ^ mul3(a2) ^ a3;
            mix_col[15:8]  = a0       ^ a1       ^ mul2(a2) ^ mul3(a3);
            mix_col[7:0]   = mul3(a0) ^ a1       ^ a2       ^ mul2(a3);
        end
    endfunction

    function automatic [127:0] mix_columns(input [127:0] s);
        mix_columns[127:96] = mix_col(s[127:96]);
        mix_columns[95:64]  = mix_col(s[95:64]);
        mix_columns[63:32]  = mix_col(s[63:32]);
        mix_columns[31:0]   = mix_col(s[31:0]);
    endfunction

    function automatic [31:0] rcon(input [3:0] r);
        reg [7:0] rc;
        begin
            case (r)
                4'd1:  rc = 8'h01; 4'd2:  rc = 8'h02; 4'd3: rc = 8'h04; 4'd4: rc = 8'h08;
                4'd5:  rc = 8'h10; 4'd6:  rc = 8'h20; 4'd7: rc = 8'h40; 4'd8: rc = 8'h80;
                4'd9:  rc = 8'h1b; 4'd10: rc = 8'h36; default: rc = 8'h00;
            endcase
            rcon = {rc, 24'h0};
        end
    endfunction

    function automatic [127:0] next_round_key(input [127:0] rk, input [3:0] r);
        reg [31:0] w0, w1, w2, w3, n0, n1, n2, n3;
        begin
            w0 = rk[127:96]; w1 = rk[95:64]; w2 = rk[63:32]; w3 = rk[31:0];
            n0 = w0 ^ subword(rotword(w3)) ^ rcon(r);
            n1 = w1 ^ n0;
            n2 = w2 ^ n1;
            n3 = w3 ^ n2;
            next_round_key = {n0, n1, n2, n3};
        end
    endfunction

    // ---- datapath / FSM ---------------------------------------------------
    reg [127:0] state;
    reg [127:0] rkey;
    reg [3:0]   round;
    reg         active;

    wire [127:0] sb = sub_bytes(state);
    wire [127:0] sr = shift_rows(sb);
    wire [127:0] mc = mix_columns(sr);

    wire         last_round = (round == 4'd10);
    wire [127:0] rkey_next  = next_round_key(rkey, round);
    // Rounds 1..9 include MixColumns; the final round omits it.
    wire [127:0] state_next = (last_round ? sr : mc) ^ rkey_next;

    always @(posedge clk) begin
        if (!rst_n) begin
            state      <= 128'h0;
            rkey       <= 128'h0;
            round      <= 4'd0;
            active     <= 1'b0;
            busy       <= 1'b0;
            done       <= 1'b0;
            ciphertext <= 128'h0;
        end else begin
            done <= 1'b0;
            if (!active) begin
                if (start) begin
                    state  <= plaintext ^ key;   // round 0: AddRoundKey
                    rkey   <= key;
                    round  <= 4'd1;
                    active <= 1'b1;
                    busy   <= 1'b1;
                end
            end else begin
                state <= state_next;
                rkey  <= rkey_next;
                if (last_round) begin
                    ciphertext <= state_next;
                    done       <= 1'b1;
                    active     <= 1'b0;
                    busy       <= 1'b0;
                    round      <= 4'd0;
                end else begin
                    round <= round + 4'd1;
                end
            end
        end
    end

endmodule

`default_nettype wire
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn report_is_correct() {
        let r = AesReport::for_variant(AesVariant::Aes128);
        assert_eq!(r.key_bits, 128);
        assert_eq!(r.rounds, 10);
        assert_eq!(r.latency_cycles, 11);
        assert_eq!(r.block_bits, 128);
        assert_eq!(r.variant_name, "AES-128");
    }

    #[test]
    fn throughput_math() {
        let r = AesReport::for_variant(AesVariant::Aes128);
        // 48 MHz / 11 cycles = 4_363_636 blocks/s * 128 bits
        assert_eq!(r.throughput_bps(48_000_000), 4_363_636 * 128);
    }

    #[test]
    fn json_is_well_formed() {
        let j = AesReport::for_variant(AesVariant::Aes128).to_json();
        assert!(j.starts_with('{') && j.ends_with('}'));
        assert!(j.contains("\"rounds\":10"));
        assert!(j.contains("\"latency_cycles\":11"));
        assert_eq!(j.matches('{').count(), j.matches('}').count());
    }

    #[test]
    fn verilog_has_expected_shape() {
        let v = generate_aes128_enc();
        assert!(v.contains("module aes128_enc"));
        assert_eq!(v.matches("endmodule").count(), 1);
        assert!(v.contains("8'h00: sbox = 8'h63;"));
        assert!(v.contains("8'hff: sbox = 8'h16;"));
        // no inferred memories -> stays portable across Yosys/Verilator
        assert!(!v.contains("reg [7:0] b [0:15]"));
        // balanced begin/end is a cheap structural smoke test
        assert!(v.contains("`default_nettype none"));
    }

    #[test]
    fn generation_is_deterministic() {
        assert_eq!(generate_aes128_enc(), generate_aes128_enc());
    }
}
