//! # Verilog Backend
//!
//! This module emits synthesizable SystemVerilog from our Module IR.
//! The output can be fed directly into:
//! - **Yosys** → open-source synthesis for iCE40, ECP5, Gowin FPGAs
//! - **Vivado** → Xilinx/AMD FPGAs
//! - **Quartus** → Intel/Altera FPGAs
//! - **Verilator** → cycle-accurate simulation (compiles to C++)
//!
//! ## Why SystemVerilog (not VHDL)?
//!
//! SystemVerilog is the dominant HDL in industry and is supported by every
//! major tool. It's also what Yosys expects as input for the open-source
//! toolchain. We can add a VHDL backend later, but SV covers 95% of use cases.

use hcp_core::prelude::*;

/// Emits SystemVerilog source code from Module definitions.
pub struct VerilogEmitter {
    /// Indentation level (2 spaces per level)
    indent: usize,
    /// The output buffer
    output: String,
}

impl VerilogEmitter {
    pub fn new() -> Self {
        VerilogEmitter {
            indent: 0,
            output: String::with_capacity(4096),
        }
    }

    /// Emit a complete module as SystemVerilog.
    pub fn emit_module(&mut self, module: &Module) -> String {
        self.output.clear();

        // File header
        self.line("// ─────────────────────────────────────────────────────────────");
        self.line(&format!("// Module: {}", module.name));
        self.line("// Generated by HCP (Hardware Context Protocol) compiler");
        self.line("// ECC-annotated signals have automatic encoder/decoder instances");
        self.line("// ─────────────────────────────────────────────────────────────");
        self.line("");

        // Module declaration
        self.emit_module_header(module);

        self.indent += 1;

        // Internal signal declarations
        self.line("");
        self.line("// Internal signals");
        for sig in &module.signals {
            self.emit_signal_declaration(sig);
        }

        // Combinational assignments
        if !module.assignments.is_empty() {
            self.line("");
            self.line("// Combinational logic");
            for assign in &module.assignments {
                self.emit_assignment(assign);
            }
        }

        // Module instances
        if !module.instances.is_empty() {
            self.line("");
            self.line("// Sub-module instances (ECC encoder/decoder)");
            for inst in &module.instances {
                self.emit_instance(inst);
            }
        }

        // Always blocks
        for block in &module.always_blocks {
            self.line("");
            self.emit_always_block(block);
        }

        self.indent -= 1;
        self.line("");
        self.line("endmodule");

        self.output.clone()
    }

    fn emit_module_header(&mut self, module: &Module) {
        self.line(&format!("module {}(", module.name));
        self.indent += 1;

        for (i, port) in module.ports.iter().enumerate() {
            let dir = match port.direction {
                PortDirection::Input => "input ",
                PortDirection::Output => "output",
                PortDirection::InOut => "inout ",
            };

            let kind = match port.signal.kind {
                SignalKind::Wire => "wire",
                SignalKind::Register => "reg ",
            };

            let width_str = if port.signal.width.bits() > 1 {
                format!("[{}:0] ", port.signal.width.bits() - 1)
            } else {
                "       ".to_string()
            };

            let comma = if i < module.ports.len() - 1 { "," } else { "" };

            self.line(&format!(
                "{} {} {}{}{} // {}",
                dir,
                kind,
                width_str,
                port.signal.name,
                comma,
                self.port_comment(port),
            ));
        }

        self.indent -= 1;
        self.line(");");
    }

    fn emit_signal_declaration(&mut self, sig: &Signal) {
        let kind = match sig.kind {
            SignalKind::Wire => "wire",
            SignalKind::Register => "reg ",
        };

        let width_str = if sig.width.bits() > 1 {
            format!("[{}:0] ", sig.width.bits() - 1)
        } else {
            "       ".to_string()
        };

        let ecc_comment = if sig.has_ecc() {
            format!(" // ECC: {:?} ({}b encoded)", sig.ecc, sig.encoded_width().bits())
        } else {
            String::new()
        };

        self.line(&format!("{} {}{};{}", kind, width_str, sig.name, ecc_comment));
    }

    fn emit_assignment(&mut self, assign: &Assignment) {
        self.line(&format!(
            "assign {} = {};",
            assign.target,
            self.expr_to_string(&assign.expression),
        ));
    }

    fn emit_instance(&mut self, inst: &Instance) {
        self.line(&format!("{} {}(", inst.module_name, inst.instance_name));
        self.indent += 1;

        for (i, (port, expr)) in inst.connections.iter().enumerate() {
            let comma = if i < inst.connections.len() - 1 { "," } else { "" };
            self.line(&format!(".{}({}){}", port, self.expr_to_string(expr), comma));
        }

        self.indent -= 1;
        self.line(");");
    }

    fn emit_always_block(&mut self, block: &AlwaysBlock) {
        let edge = match block.edge {
            ClockEdge::Rising => "posedge",
            ClockEdge::Falling => "negedge",
        };

        let sensitivity = if let Some(ref rst) = block.reset {
            if !rst.synchronous {
                format!(
                    "always @({} {} or {} {})",
                    edge,
                    block.clock,
                    if rst.active_high { "posedge" } else { "negedge" },
                    rst.signal,
                )
            } else {
                format!("always @({} {})", edge, block.clock)
            }
        } else {
            format!("always @({} {})", edge, block.clock)
        };

        self.line(&format!("{} begin", sensitivity));
        self.indent += 1;

        // Reset logic
        if let Some(ref rst) = block.reset {
            let condition = if rst.active_high {
                rst.signal.clone()
            } else {
                format!("!{}", rst.signal)
            };
            self.line(&format!("if ({}) begin", condition));
            self.indent += 1;
            self.line("// Reset values would go here");
            self.indent -= 1;
            self.line("end else begin");
            self.indent += 1;
        }

        for stmt in &block.statements {
            self.emit_statement(stmt);
        }

        if block.reset.is_some() {
            self.indent -= 1;
            self.line("end");
        }

        self.indent -= 1;
        self.line("end");
    }

    fn emit_statement(&mut self, stmt: &Statement) {
        match stmt {
            Statement::Assign { target, value } => {
                self.line(&format!(
                    "{} <= {};",
                    target,
                    self.expr_to_string(value),
                ));
            }
            Statement::If {
                condition,
                then_body,
                else_body,
            } => {
                self.line(&format!("if ({}) begin", self.expr_to_string(condition)));
                self.indent += 1;
                for s in then_body {
                    self.emit_statement(s);
                }
                self.indent -= 1;
                if !else_body.is_empty() {
                    self.line("end else begin");
                    self.indent += 1;
                    for s in else_body {
                        self.emit_statement(s);
                    }
                    self.indent -= 1;
                }
                self.line("end");
            }
        }
    }

    fn expr_to_string(&self, expr: &Expr) -> String {
        match expr {
            Expr::Literal { value, width } => format!("{}'d{}", width, value),
            Expr::Signal(name) => name.clone(),
            Expr::BinOp { op, left, right } => {
                let op_str = match op {
                    BinOpKind::Add => "+",
                    BinOpKind::Sub => "-",
                    BinOpKind::Mul => "*",
                    BinOpKind::And => "&",
                    BinOpKind::Or => "|",
                    BinOpKind::Xor => "^",
                    BinOpKind::Eq => "==",
                    BinOpKind::Ne => "!=",
                    BinOpKind::Lt => "<",
                    BinOpKind::Gt => ">",
                    BinOpKind::Le => "<=",
                    BinOpKind::Ge => ">=",
                    BinOpKind::Shl => "<<",
                    BinOpKind::Shr => ">>",
                };
                format!(
                    "({} {} {})",
                    self.expr_to_string(left),
                    op_str,
                    self.expr_to_string(right),
                )
            }
            Expr::UnOp { op, operand } => {
                let op_str = match op {
                    UnOpKind::Not => "~",
                    UnOpKind::ReduceXor => "^",
                };
                format!("{}({})", op_str, self.expr_to_string(operand))
            }
            Expr::Slice { signal, high, low } => {
                if high == low {
                    format!("{}[{}]", signal, high)
                } else {
                    format!("{}[{}:{}]", signal, high, low)
                }
            }
            Expr::Concat(parts) => {
                let parts_str: Vec<String> =
                    parts.iter().map(|p| self.expr_to_string(p)).collect();
                format!("{{{}}}", parts_str.join(", "))
            }
        }
    }

    fn port_comment(&self, port: &Port) -> String {
        let mut parts = Vec::new();
        if port.signal.has_ecc() {
            parts.push(format!("ECC: {:?}", port.signal.ecc));
        }
        if parts.is_empty() {
            String::new()
        } else {
            parts.join(", ")
        }
    }

    fn line(&mut self, text: &str) {
        for _ in 0..self.indent {
            self.output.push_str("  ");
        }
        self.output.push_str(text);
        self.output.push('\n');
    }
}

impl Default for VerilogEmitter {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_emit_simple_module() {
        let mut m = Module::new("test_mod");
        m.add_input("clk", 1);
        m.add_input("data_in", 8);
        m.add_output("data_out", 8);

        let mut emitter = VerilogEmitter::new();
        let sv = emitter.emit_module(&m);

        assert!(sv.contains("module test_mod("));
        assert!(sv.contains("input "));
        assert!(sv.contains("output"));
        assert!(sv.contains("endmodule"));
        println!("{}", sv);
    }

    #[test]
    fn test_emit_module_with_ecc_instances() {
        let mut m = Module::with_ecc("counter", EccScheme::HammingSecDed);
        m.add_input("clk", 1);
        m.add_input("rst", 1);
        m.add_output_reg("count", 8);

        // Run ECC pass
        let result = crate::ecc_pass::EccPass::run(&m);

        let mut emitter = VerilogEmitter::new();

        // Emit supporting modules
        for enc in &result.encoder_modules {
            let sv = emitter.emit_module(enc);
            println!("=== ENCODER ===\n{}", sv);
            assert!(sv.contains("hamming_enc_8"));
        }

        for dec in &result.decoder_modules {
            let sv = emitter.emit_module(dec);
            println!("=== DECODER ===\n{}", sv);
            assert!(sv.contains("hamming_dec_8"));
        }

        // Emit the main module
        let sv = emitter.emit_module(&result.module);
        println!("=== MAIN MODULE ===\n{}", sv);
        assert!(sv.contains("enc_count"));
        assert!(sv.contains("dec_count"));
        assert!(sv.contains("err_correctable"));
    }
}
